apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-server
    spec:
      containers:
      - name: hello-world-server
        image: mrgitics/hello-world-server:v1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort
