name: Build and Push Docker Image

on:
   push:
     tags:
       - 'v*'

jobs:
  docker:
    if: ${{ github.ref == 'task-3-ci-pipeline' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: yourusername/hello-world-server:${{ github.ref_name }}
